Initialize project
Hospital-Database/Frontend pull request #1
Opened 2024-04-13 20:22 UTC by mohamedahmed-cloud

2024-04-13 22:21 UTC, mohamedahmed-cloud commented
all thing ok

2024-04-13 22:23 UTC, mohamedahmed-cloud commented on lefthook.yml
> +      run: npx biome format --no-errors-on-unmatched --files-ignore-unknown=true "{staged_files}" && git update-index --again
very good work

2024-04-13 22:23 UTC, mohamedahmed-cloud commented on middleware.ts
> +};
very good work

2024-04-14 09:24 UTC, MuhammadSawalhy requested changes

2024-04-14 09:24 UTC, MuhammadSawalhy commented on lefthook.yml
`biome check` already does the formatting, check [this](https://biomejs.dev/recipes/git-hooks/#lefthook).

2024-04-14 09:24 UTC, MuhammadSawalhy commented on .eslintrc.json
No need to Eslint, you used Biome!

2024-04-14 09:24 UTC, MuhammadSawalhy commented on package-lock.json
No need for package-lock if you are using pnpm

2024-04-14 09:24 UTC, MuhammadSawalhy commented on i18n/config.json
Why this?

2024-04-14 10:37 UTC, mohamedahmed-cloud commented on lefthook.yml
I read it but didn't notice that it is used to `format and lint before committing`.😥
so to make formatting without checking linter we can use `format --write` as it [is](https://biomejs.dev/formatter/) and the question here is how to make formatting without checking linter?
 Docs [here](https://biomejs.dev/linter/) said we use check to check linter `not to check linter and formatting`

2024-04-14 10:45 UTC, mohamedahmed-cloud commented on i18n/config.json
- When trying to search the best practice to use `next-intl`, I found [this](https://github.com/nodejs/nodejs.org/blob/main/i18n/config.json) 
- Mainly is used to get all the info about current locale like `lang` & `page-direction` if we use more than two language it will be so useful

2024-04-14 10:49 UTC, mohamedahmed-cloud commented on i18n/config.json
take a look at this [next.locales.mjs](https://github.com/Hospital-Database/Frontend/pull/1/files/deb28620de46999849b4f91eb8c6395e635f3a26#diff-18c049b08c4a0f5ab451c598aeb2c4848bb9d7877b51ca3e5effb94a225814d2) & [layout.ts](https://github.com/Hospital-Database/Frontend/pull/1/files/deb28620de46999849b4f91eb8c6395e635f3a26#diff-44ca66e460fac15e804a2ab56f6038ef2dd0a231881294f0a3895f9ad7624c58)

2024-04-14 17:31 UTC, MuhammadSawalhy commented on lefthook.yml
I tried `biome check` locally and the file was formatted and linted.

2024-04-14 17:31 UTC, MuhammadSawalhy commented on i18n/config.json
Great

2024-04-15 08:47 UTC, mohamed-ahmed-yousef commented on .eslintrc.json
- Eslint Must be installed to run command `pnpm run build` 
![image](https://github.com/Hospital-Database/Frontend/assets/81932663/873b6934-d7d2-4949-a548-2b26221afd78)

2024-04-16 16:32 UTC, MuhammadSawalhy approved these changes

2024-04-16 16:32 UTC, merged